<?php

/**
 * GEOSERVER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * GEOSERVER API
 * @version 0.0.1
 */

$app->get('/', function () use ($app) {
    return $app->version();
});

/**
 * POST login
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->POST('/api/login', 'AuthApi@login');
/**
 * GET logout
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->GET('/api/signout', 'AuthApi@logout');

