<?php

/**
 * GEOSERVER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class AuthApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation login
     *
     * .
     *
     *
     * @return Http response
     */
    public function login()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling login');
        }
        $body = $input['body'];


        return response('How about implementing login as a POST method ?');
    }
    /**
     * Operation logout
     *
     * .
     *
     *
     * @return Http response
     */
    public function logout()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing logout as a GET method ?');
    }
}
